# Generated by Django 5.0.4 on 2024-04-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=16, unique=True, verbose_name='Telefon')),
                ('activated_date', models.DateTimeField(blank=True, null=True, verbose_name='Aktivlashgan Vaqti')),
                ('is_seller', models.BooleanField(default=False, verbose_name='Sotuvchilik holati')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktivligi')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('register', 'register'), ('resend', 'resend'), ('change_phone', 'change_phone'), ('password_reset', 'password_reset')], default='register', max_length=30, verbose_name='Kod tasdiqlash turi')),
                ('code', models.CharField(max_length=6, verbose_name='Tasdiqlash Kod')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Kodning so'rov vaqti")),
                ('expiration_time', models.DateTimeField(editable=False, verbose_name='Yaroqlilik muddati')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Tasdiqlanganligi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Familiya')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yhatdan o'tgan vaqti")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Manzil sarlavhasi')),
                ('country', models.CharField(max_length=50, verbose_name='Mamlakat')),
                ('province', models.CharField(max_length=50, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=50, verbose_name='Shahar / Tuman')),
                ('street', models.CharField(max_length=50, verbose_name="Ko'cha nomi va uy raqami")),
                ('zip_code', models.IntegerField(verbose_name='Pochta Indeksi')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='accounts.profile')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.uploadfile')),
            ],
        ),
    ]
